import type { Metadata } from 'next'
import { Syne } from 'next/font/google'
import './globals.css'
import { Header } from './_components/ui/header'
import { Footer } from './_components/ui/footer'

const syne = Syne({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NextAge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pt-BR'>
      <body className={syne.className}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  )
}
